"""Declarative base for all ORM models.

The naming convention gives every constraint a predictable name. Without it
Alembic falls back to database-generated names, which makes autogenerated
migrations noisy and harder to review.
"""

from enum import Enum as StdEnum

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# See https://alembic.sqlalchemy.org/en/latest/naming.html
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def enum_values(enum_cls: type[StdEnum]) -> list[str]:
    """Persist enum values (e.g. 'breakfast'), not member names (e.g. 'BREAKFAST').

    Passed as ``values_callable`` to a non-native SQLAlchemy ``Enum`` column so the
    stored value is the neutral domain string, not the Python member name.
    """
    return [member.value for member in enum_cls.__members__.values()]
