"""Declarative base for all ORM models.

The naming convention gives every constraint a predictable name. Without it
Alembic falls back to database-generated names, which makes autogenerated
migrations noisy and harder to review.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# See https://alembic.sqlalchemy.org/en/latest/naming.html
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
