"""describe change

Revision ID: 1b3cc6d8854b
Revises: f7b2c4e91a35
Create Date: 2026-06-23 12:46:28.026537

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1b3cc6d8854b'
down_revision: str | Sequence[str] | None = 'f7b2c4e91a35'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
